USE [VuMaxDR]
GO

/****** Object:  Table [dbo].[eVuMaxBroomStickDocs]    Script Date: 2/21/2022 3:19:11 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[eVuMaxBroomStickDocs](
	[DOC_ID] [varchar](50) NOT NULL,
	[WELL_ID] [varchar](50) NOT NULL,
	[USER_ID] [varchar](50) NOT NULL,
	[DOC_TYPE] [int] NULL,
	[DOC_NAME] [varchar](100) NULL,
	[SETUP] [ntext] NULL,
	[TIME_FILTER] [ntext] NULL,
 CONSTRAINT [PK_eVuMaxBroomStickDocs] PRIMARY KEY CLUSTERED 
(
	[DOC_ID] ASC,
	[WELL_ID] ASC,
	[USER_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO


